
server:
  port: 8083

spring:
  application:
     name: Apigateway
  cloud:
    gateway:
      routes:
      - id: dealerapi
        uri: http://localhost:8080/
        predicates:
        - Path=/dealer/**
      - id: farmerapi
        uri: http://localhost:8081/
        predicates:
        - Path=/farmer/**