server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
     name: Apigateway
  cloud:
    gateway:
      routes:
      - id: dealerapi
        uri: http://dealerApi/
        predicates:
        - Path=/dealer/**
      - id: farmerApi 
        uri: http://localhost:8082/
        predicates:
        - Path=/farmer/**
      - id: cropapi
        uri: lb://crop-avalilable/
        predicates:
        - Path=/crops/**
      - id: admin
        uri: http://admin/
        predicates:
        - Path=/admin/**  