
server:
  port: 8083

spring:
  application:
     name: Apigateway
  cloud:
    gateway:
      routes:
      - id: dealerapi
        uri: lb://DealerApi/
        predicates:
        - Path=/dealer/**
      - id: farmerapi 
        uri: http://localhost:8081/
        predicates:
        - Path=/farmer/**
      - id: cropapi
        uri: lb://crop-avalilable/
        predicates:
        - Path=/crops/**
      - id: cropapi
        uri: http://localhost:8089/
        predicates:
        - Path=/admin/**  